(ns net.brdloush.livewire.trace
  "Tracing tools: capture SQL execution natively without P6Spy."
  (:import [net.brdloush.livewire LivewireSqlTracer LivewireSqlTracer$TraceEntry]))

(defn unpack-entries [entries]
  (mapv (fn [^LivewireSqlTracer$TraceEntry e]
          {:sql (.-sql e)
           :caller (.-caller e)})
        entries))

(defmacro trace-sql
  "Executes body and captures all SQL statements generated by Hibernate on the current thread.
   Returns a map with :result, :queries, :count, and :duration-ms.
   Useful for standard, synchronous code."
  [& body]
  `(do
     (LivewireSqlTracer/startThreadLocalTrace)
     (let [start# (System/currentTimeMillis)]
       (try
         (let [result# (do ~@body)
               duration# (- (System/currentTimeMillis) start#)
               queries# (unpack-entries (LivewireSqlTracer/stopThreadLocalTrace))]
           {:result result#
            :queries queries#
            :count (count queries#)
            :duration-ms duration#})
         (catch Exception e#
           (LivewireSqlTracer/stopThreadLocalTrace)
           (throw e#))))))

(defmacro trace-sql-global
  "Executes body and captures *all* SQL statements generated by Hibernate on the JVM.
   Returns a map with :result, :queries, :count, and :duration-ms.
   Useful when debugging asynchronous operations (e.g., @Async, CompletableFuture)."
  [& body]
  `(do
     (LivewireSqlTracer/startGlobalTrace)
     (let [start# (System/currentTimeMillis)]
       (try
         (let [result# (do ~@body)
               duration# (- (System/currentTimeMillis) start#)
               queries# (unpack-entries (LivewireSqlTracer/stopGlobalTrace))]
           {:result result#
            :queries queries#
            :count (count queries#)
            :duration-ms duration#})
         (catch Exception e#
           (LivewireSqlTracer/stopGlobalTrace)
           (throw e#))))))

(defn detect-n+1
  "Analyzes a trace result (from `trace-sql` or `trace-sql-global`) and
   flags any queries that were executed repeatedly.

   Returns a map with `:suspicious-queries` containing queries that ran
   more than the `threshold` times (defaults to 3), sorted by execution count."
  ([trace-result]
   (detect-n+1 trace-result 3))
  ([trace-result threshold]
   (let [queries (:queries trace-result)
         ;; Group by identical sql+caller signature (both fields together).
         ;; Using sql alone would merge queries that happen to have the same text
         ;; but originate from different call sites, masking the true source of
         ;; each repetition.  Keeping the caller in the key means each distinct
         ;; (sql, caller) pair is counted independently — intentional.
         freqs (frequencies queries)
         suspicious (->> freqs
                         (filter (fn [[_ count]] (> count threshold)))
                         (sort-by val >)
                         (mapv (fn [[query-info count]]
                                 (assoc query-info :count count))))]
     {:suspicious-queries suspicious
      :total-queries (:count trace-result)
      :duration-ms (:duration-ms trace-result)})))
