(ns net.brdloush.livewire.trace
  "Tracing tools: capture SQL execution natively without P6Spy."
  (:import [net.brdloush.livewire LivewireSqlTracer]))

(defmacro trace-sql
  "Executes body and captures all SQL statements generated by Hibernate on the current thread.
   Returns a map with :result, :queries, :count, and :duration-ms.
   Useful for standard, synchronous code."
  [& body]
  `(do
     (LivewireSqlTracer/startThreadLocalTrace)
     (let [start# (System/currentTimeMillis)]
       (try
         (let [result# (do ~@body)
               duration# (- (System/currentTimeMillis) start#)
               queries# (vec (LivewireSqlTracer/stopThreadLocalTrace))]
           {:result result#
            :queries queries#
            :count (count queries#)
            :duration-ms duration#})
         (catch Exception e#
           (LivewireSqlTracer/stopThreadLocalTrace)
           (throw e#))))))

(defmacro trace-sql-global
  "Executes body and captures *all* SQL statements generated by Hibernate on the JVM.
   Returns a map with :result, :queries, :count, and :duration-ms.
   Useful when debugging asynchronous operations (e.g., @Async, CompletableFuture)."
  [& body]
  `(do
     (LivewireSqlTracer/startGlobalTrace)
     (let [start# (System/currentTimeMillis)]
       (try
         (let [result# (do ~@body)
               duration# (- (System/currentTimeMillis) start#)
               queries# (vec (LivewireSqlTracer/stopGlobalTrace))]
           {:result result#
            :queries queries#
            :count (count queries#)
            :duration-ms duration#})
         (catch Exception e#
           (LivewireSqlTracer/stopGlobalTrace)
           (throw e#))))))
